config/routes.rb
Rails.application.routes.draw do
  get 'login' => 'sessions#new'
  delete 'logout' => 'sessions#destroy'
  resources :sessions, only: [:new, :create, :destroy]

  resources :quarters
  resources :graves do
    get :names, on: :collection
    get :links, on: :collection
  end
  resources :people do
    post :search, on: :collection
  end

  root 'people#index'

end

app/models/quarter.rb
class Quarter < ActiveRecord::Base
  has_many :graves, dependent: :destroy
  validates :name, :short_name, presence: true, uniqueness: true

  def self.sort_by_name(array)
    # it should  be sorted like this
    # ["Kwatera 3", "Kwatera 14", "Pas 2"]
    array.sort do |a, b|
      # compare each word
      splited_pairs = a.name.split.zip(b.name.split)
      # find first different pair
      part_a, part_b = splited_pairs.drop_while { |aa, bb| aa == bb }.first
      if part_a =~ /\A\d+\z/ && part_b =~ /\A\d+\z/ # both are numbers
        part_a.to_i <=> part_b.to_i        # compare numeric values
      else
        part_a.to_s <=> part_b.to_s        # compare alphabetically
      end
    end
  end

  def self.create_from_short_name!(sn)
    name =
      if sn =~ /\Ak(\d+)\z/
        "Kwatera #{$+}"
      elsif sn =~ /\Ap(\d+)\z/
        "Pas #{$+}"
      end
    Quarter.create!(name: name, short_name: sn)
  end
end

app/controllers/quarters_controller.rb
class QuartersController < ApplicationController
  before_action :authorize, except: [:index, :show]

  def index
    @quarters = Quarter.sort_by_name(Quarter.all)
  end

  def show
    @quarter = Quarter.find(params[:id])
    @graves = @quarter.graves
  end

  def new
    @quarter = Quarter.new
  end

  def create
    @quarter = Quarter.new(quarter_params)
    if @quarter.save
      redirect_to @quarter, notice: create_notice(:quarter)
    else
      render :new
    end
  end

  def edit
    @quarter = Quarter.find(params[:id])
  end

  def update
    @quarter = Quarter.find(params[:id])
    if @quarter.update(quarter_params)
      redirect_to @quarter, notice: update_notice(:quarter)
    else
      render :edit
    end
  end

  def destroy
    Quarter.find(params[:id]).destroy
    redirect_to quarters_path, notice: destroy_notice(:quarter)
  end

  private

  def quarter_params
    params.require(:quarter).permit(:name, :short_name)
  end
end

app/helpers/quarters_helper.rb
module QuartersHelper
end

app/views/quarters/_form.html.haml
= simple_form_for @quarter do |f|
  = f.input :name
  = f.input :short_name
  
  .form-actions
    = f.submit nil, class: 'btn btn-primary'
    = cancel_link(@quarter.new_record? ? quarters_path : quarter_path(@quarter))

app/views/quarters/index.html.haml
- set_title

- if admin?
  = link_to t('.new'), new_quarter_path, class: 'btn btn-primary right'
  
.page-header
  %h1= t '.title'
  
- @quarters.each do |quarter|
  %p
    = link_with_name quarter

app/views/quarters/show.html.haml
- set_title @quarter.name
.page-header
  %h1= @quarter.name

- if admin?
  %p
    = field_label :short_name
    = @quarter.short_name

- if @graves.any?
  %p
    = field_label :graves
    - @graves.sort.each do |grave|
      = link_to grave.number, grave

- if admin?
  .form-actions
  = edit_btn edit_quarter_path(@quarter)
  = delete_btn @quarter