config/routes.rb
Rails.application.routes.draw do
  get 'login' => 'sessions#new'
  delete 'logout' => 'sessions#destroy'
  resources :sessions, only: [:new, :create, :destroy]

  resources :quarters
  resources :graves do
    get :names, on: :collection
    get :links, on: :collection
  end
  resources :people do
    post :search, on: :collection
  end

  root 'people#index'

end

app/models/person.rb
class Person < ActiveRecord::Base
  include DataState

  PUBLIC_ATTRIBUTES = [:first_name, :last_name, :family_name, :birth_date,
                       :death_date, :lived, :description]

  FIELDS = [:first_name, :last_name, :family_name, :lived, :raw_record,
            :data_state, :notes]

  belongs_to :grave
  validates :lived, numericality: { greater_than_or_equal_to: 0 }, allow_nil: true
  has_one :birth_date, dependent: :destroy
  has_one :death_date, dependent: :destroy
  validate :birth_before_death

  # select only people with some publicly accessible information
  def self.any_info
    includes(:birth_date).includes(:death_date).includes(:grave)
      .joins('LEFT JOIN birth_dates ON birth_dates.person_id = people.id')
      .joins('LEFT JOIN death_dates ON death_dates.person_id = people.id')
      .where("first_name IS NOT NULL OR last_name IS NOT NULL \
           OR family_name IS NOT NULL OR lived IS NOT NULL \
           OR description IS NOT NULL OR birth_dates.year IS NOT NULL \
           OR death_dates.year IS NOT NULL").order(:last_name)
  end

  def self.search(phrase)
    where 'LOWER(first_name) LIKE ? OR LOWER(last_name) LIKE ? OR LOWER(family_name) LIKE ?',
      "%#{phrase.strip.downcase}%", "%#{phrase.strip.downcase}%", "%#{phrase.strip.downcase}%"
  end

  def full_name
    if [first_name, last_name, family_name].any?(&:present?)
      [first_name, last_name, family_name_in_parenthesis].compact.join(' ')
    else
      'Nieznane'
    end
  end

  def to_param
    "#{id} #{full_name}".parameterize
  end

  def errors_with_dates?
    errors.any? || (birth_date && birth_date.errors.any?) ||
      (death_date && death_date.errors.any?)
  end

  def quarter
    grave.quarter if grave
  end

  def quarter_graves
    quarter ? quarter.graves.sort : Grave.quarterless.sort
  end

  private

  def family_name_in_parenthesis
    "(#{family_name})" if family_name.present?
  end

  def birth_before_death
    birth_date_ok = birth_date && !birth_date.destroyed? && birth_date.valid?
    death_date_ok = death_date && !death_date.destroyed? && death_date.valid?
    return unless birth_date_ok && death_date_ok && !birth_date.could_be_before(death_date)

    errors[:base] << I18n.t('errors.death_before_birth',
                            default: 'A man must be born before he dies')
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :authorize, except: [:index, :show, :search]

  def index
    @people = Person.any_info.paginate(page: params[:page])
  end

  def show
    @person = Person.find(params[:id])
  end

  def new
    @person = Person.new
  end

  def create
    @person = Person.new
    setting = PersonSetting.new(@person, person_params, birth_params, death_params)
    if setting.create
      redirect_to @person, notice: create_notice(:person)
    else
      render :new
    end
  end

  def edit
    @person = Person.find(params[:id])
  end

  def update
    @person = Person.find(params[:id])
    setting = PersonSetting.new(@person, person_params, birth_params, death_params)
    if setting.update
      redirect_to @person, notice: update_notice(:person)
    else
      render :edit
    end
  end

  def destroy
    Person.find(params[:id]).destroy
    redirect_to people_path, notice: destroy_notice(:person)
  end

  def search
    @people = Person.search(params[:search])
    render json: @people
  end

  private

  def person_params
    params.require(:person).permit(
      :first_name, :last_name, :family_name, :lived, :raw_record,
      { data_state: [] }, :description, :notes, :grave_id
    )
  end

  def birth_params
    params.require(:person).require(:birth_date).permit(:year, :month, :day)
  end

  def death_params
    params.require(:person).require(:death_date).permit(:year, :month, :day)
  end
end

app/helpers/people_helper.rb
module PeopleHelper
  def quarter_select_options
    {
      collection: Quarter.all,
      value_method: :id,
      selected: (@person.quarter.id if @person.quarter),
      include_blank: true
    }
  end
end

app/views/people/_date_fields.html.haml
%p.hint= t 'simple_form.labels.defaults.date_hint'
- if f.object && f.object.errors.any?
  .error_list
    - f.object.errors.full_messages.each do |msg|
      = msg
      %br

= f.number_field :day, class: :day
= '-'
= f.number_field :month, class: :month
= '-'
= f.number_field :year, class: :year

app/views/people/_form.html.haml
= render 'shared/errors', messages:  @person.errors[:base],
                          show_info: @person.errors_with_dates?

= simple_form_for @person do |f|
  = f.input :quarter, quarter_select_options
  = f.association :grave, collection: @person.quarter_graves
  = f.input :first_name
  = f.input :last_name
  = f.input :family_name
  = f.input :lived
  = f.input :description
  = f.input :raw_record
  = f.label :data_state
  %br
  = f.collection_check_boxes :data_state, Person.check_boxes_array, :first, :last
  = f.input :notes
  
  = f.label :birth_date
  %br
  = f.fields_for :birth_date, @person.birth_date do |bd|
    = render 'date_fields', f: bd
    
  %br
  = f.label :death_date
  %br
  = f.fields_for :death_date, @person.death_date do |dd|
    = render 'date_fields', f: dd
  
  .form-actions
    = f.submit nil, class: 'btn btn-primary'
    = cancel_link(@person.new_record? ? people_path : person_path(@person))

app/views/people/edit.html.haml
- set_title
.page-header
  %h1= t '.title'
= render partial: "form"

app/views/people/index.html.haml
- set_title

- if admin?
  = link_to t('.new'), new_person_path, class: 'btn btn-primary right'

.page-header.people
  %h1= t '.title'

= form_tag search_people_path, method: :post do
  = text_field_tag :search, params[:search]
  = submit_tag t('.search'), name: nil, class: 'btn'

%table.table.table-striped#people
  %thead
    %tr
      %th= t '.name'
      %th= t '.birth'
      %th= t '.death'
      %th= t '.grave'
      - if admin?
        %th= t 'helpers.actions'
  %tbody
    - @people.each do |person|
      %tr
        %td= link_to person.full_name, person
        %td= person.birth_date
        %td= person.death_date
        %td= link_to t('.grave'), person.grave
        - if admin?
          %td
            = edit_btn(edit_person_path(person), class: 'btn btn-mini')
            = delete_btn(person, class: 'btn btn-mini btn-danger')

= will_paginate

app/views/people/new.html.haml
- set_title
.page-header
  %h1= t '.title'
= render partial: "form"

app/views/people/show.html.haml
- set_title @person.full_name

.page-header
  %h1= @person.full_name

- Person::PUBLIC_ATTRIBUTES.each do |attr|
  - if @person.send(attr).present?
    %p
      = field_label attr
      = @person.send(attr)

- if @person.grave
  %p
    = field_label :grave
    = link_with_name @person.grave

- if admin?
  - admin_attrs = [:notes, :raw_record]
  - admin_attrs.each do |attr|
    - if @person.send(attr).present?
      %p
        = field_label attr
        = @person.send(attr)
  %p
    = field_label :data_state
    = @person.data_states
    
  .form-actions
    = edit_btn edit_person_path(@person)
    = delete_btn @person