config/routes.rb
Rails.application.routes.draw do
  get 'login' => 'sessions#new'
  delete 'logout' => 'sessions#destroy'
  resources :sessions, only: [:new, :create, :destroy]

  resources :quarters
  resources :graves do
    get :names, on: :collection
    get :links, on: :collection
  end
  resources :people do
    post :search, on: :collection
  end

  root 'people#index'

end

app/models/grave.rb
class Grave < ActiveRecord::Base
  include DataState
  include Comparable

  has_many :people, dependent: :destroy
  belongs_to :quarter
  validates :number, presence: true, uniqueness: { scope: :quarter_id }
  validate :nonnegative_number

  enum grave_type: { single: 0, family: 1 }

  scope :quarterless, -> { where quarter: nil }

  def self.names(quarter_id)
    graves =
      if quarter_id.present?
        where(quarter_id: quarter_id).sort
      else
        quarterless.sort
      end

    graves.map { |g| { id: g.id, name: g.name } }
    # graves.map do |grave|
    #   {
    #     id: grave.id,
    #     name: grave.name,
    #     path: Rails.application.routes.url_helpers.grave_path(grave)
    #   }
    # end.to_json
  end

  # it shouldn't be callback, user should be able to set grave type as he wants
  def set_grave_type!
    if people.count > 1
      family!
    else
      single!
    end
  end

  def <=>(other)
    return unless other.is_a? Grave

    if quarter_id == other.quarter_id
      compare_numbers(other)
    else
      quarter_id <=> other.quarter_id
    end
  end

  def name
    int?(number) ? "Grób nr #{number}" : number
  end

  private

  def int?(str)
    Integer(str)
  rescue
    false
  end

  def to_int(str)
    Integer(str)
  rescue
    -1
  end

  def nonnegative_number
    errors[:number] << "can't be negative" if int?(number) && number.to_i < 0
  end

  def compare_numbers(other)
    # graves where 'number' is a name like "Tomb of the Unknown Soldier"
    # should be listed first - to_int returns -1

    if int?(number) || int?(other.number)
      to_int(number) <=> to_int(other.number)
    else
      number <=> other.number
    end
  end
end

app/controllers/graves_controller.rb
class GravesController < ApplicationController
  before_action :authorize, except: [:index, :show]

  def index
    @quarters = Quarter.includes(:graves).select { |q| q.graves.any? }
    @quarters = Quarter.sort_by_name(@quarters)
    @quarterless = Grave.quarterless.sort
  end

  def show
    @grave = Grave.find(params[:id])
  end

  def new
    @grave = Grave.new
  end

  def create
    @grave = Grave.new(grave_params)
    if @grave.save
      redirect_to @grave, notice: create_notice(:grave)
    else
      render :new
    end
  end

  def edit
    @grave = Grave.find(params[:id])
  end

  def update
    @grave = Grave.find(params[:id])
    if @grave.update(grave_params)
      redirect_to @grave, notice: update_notice(:grave)
    else
      render :edit
    end
  end

  def destroy
    Grave.find(params[:id]).destroy
    redirect_to graves_path, notice: destroy_notice(:grave)
  end

  def names
    graves = Grave.names(params[:quarter_id])
    render json: graves
  end

  def links
    quarter_id = params[:quarter_id]
    # puts quarter_id
    @graves = Grave.where(quarter_id: quarter_id)
    @quarter = Quarter.find(quarter_id)
    # format.js
    # respond_to do |format|
    #   format.json { render json: @graves }
    #   format.js
    # end
  end

  private

  def grave_params
    params.require(:grave).permit(:quarter_id, :number, :description, :notes,
                                  :grave_type, :family_name, :data_state)
  end
end

app/helpers/graves_helper.rb
module GravesHelper
end

app/views/graves/_form.html.haml
= simple_form_for @grave do |f|
  = f.association :quarter
  = f.input :number
  = f.input :description
  = f.input :family_name
  = f.input :notes

  .form-actions
    = f.submit nil, class: 'btn btn-primary'
    = cancel_link(@grave.new_record? ? graves_path : grave_path(@grave))

app/views/graves/_grave.html.haml
= link_to grave.number, grave, class: 'grave'

app/views/graves/index.html.haml
- set_title

- if admin?
  = link_to t('.new'), new_grave_path, class: 'btn btn-primary right'

.page-header
  %h1= t '.title'

- @quarters.each do |quarter|
  %h2= link_with_name quarter

  = div_for quarter do
    = render quarter.graves.sort.take(10)
    - if quarter.graves.length > 10
      = link_to t('.show_all'), links_graves_path(quarter_id: quarter.id), remote: true

- if @quarterless.any?
  %h2= t '.quarterless'
  - @quarterless.take(10).each do |grave|
    = link_to grave.number, grave

app/views/graves/links.js.erb
$('#<%= dom_id(@quarter) %>').html("<%= escape_javascript(render @graves) %>");

app/views/graves/names.js.erb
var quarter = $('#<%= dom_id(@quarter)%>');
quarter.empty();
var graves = $.parseJSON("<%= escape_javascript(@graves) %>");
var grave_links = $.map(graves, function(grave, id) {
  $('<a>', {
    text: grave.name,
    href: grave.path,
    class: 'grave'
  });
});
quarter.append(grave_links);

app/views/graves/show.html.haml
.page-header
  %h1= @grave.name

%p
  = field_label :quarter
  = @grave.quarter ? (link_with_name @grave.quarter) : t('.no_quarter')

%p
  = field_label :number
  = @grave.number

- if @grave.description.present?
  %p
    = field_label :description
    = @grave.description
  
- if @grave.people.any?
  %p
    = field_label :people, no_br: true
    - @grave.people.each do |person|
      %br
      = link_to person.full_name, person
  
- if admin?
  
  %p
    = field_label :family_name
    = @grave.family_name
  %p
    = field_label :notes
    = @grave.notes
  
  .form-actions
    = edit_btn edit_grave_path(@grave)
    = delete_btn @grave