config/routes.rb
Rails.application.routes.draw do
  get 'login' => 'sessions#new'
  delete 'logout' => 'sessions#destroy'
  resources :sessions, only: [:new, :create, :destroy]

  resources :quarters
  resources :graves do
    get :names, on: :collection
    get :links, on: :collection
  end
  resources :people do
    post :search, on: :collection
  end

  root 'people#index'

end

app/views/layouts/_header.html.haml
%nav.navbar.navbar-default{role: "navigation"}
  .container-fluid
    .navbar-header
      %button.navbar-toggle{type: "button", "data-toggle" => "collapse",
                            "data-target" => "#bs-example-navbar-collapse-1"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to t('menu.main'), root_url, class: 'navbar-brand'
      
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li= link_to t('menu.people'), people_path
        %li= link_to t('menu.graves'), graves_path
        %li= link_to t('menu.quarters'), quarters_path
        %li= link_to t('menu.gallery'), '#'
      - if admin?
        %ul.nav.navbar-nav.navbar-right
          %li= link_to t('menu.logout'), logout_path, method: "delete"

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title= page_title(yield(:title))
    = stylesheet_link_tag 'application', media: 'all',
                                         'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    /[if lt IE 9]
      %script{src: "http://html5shim.googlecode.com/svn/trunk/html5.js",
              type: "text/javascript"}
    %meta{name: "viewport", content: "width=device-width, initial-scale=1.0"}
  %body{class: "#{ controller_name } #{ action_name }"}
    = render 'layouts/header'
    .container
      - flash.each do |key, msg|
        = alert_box(key, msg)
      = yield